---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubeassist-operator
  namespace: kubeassist-operator-system
spec:
  channel: alpha
  name: kubeassist-operator
  source: kubeassist-operator-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic
